--------------------------------------------------------
--  Fichier cr�� - jeudi-d�cembre-17-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence IDAI
--------------------------------------------------------

   CREATE SEQUENCE "IDAI"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence IDFORMATION_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE "IDFORMATION_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence IDPROJET_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE "IDPROJET_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MATRICULEIA
--------------------------------------------------------

   CREATE SEQUENCE "MATRICULEIA"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "CLIENT" 
   (	"ID_CLIENT" VARCHAR2(20 CHAR), 
	"QUANTITE" VARCHAR2(20 CHAR), 
	"STATUT" VARCHAR2(20 CHAR), 
	"PRODUIT_ACHETE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "COMMANDE" 
   (	"ID_COMMANDE" VARCHAR2(20 CHAR), 
	"QUANTITE" VARCHAR2(20 CHAR), 
	"REF_PRODUIT" VARCHAR2(20 CHAR), 
	"ID_CLIENT" VARCHAR2(20 CHAR), 
	"DATE_COMMANDE" VARCHAR2(20 CHAR), 
	"ETAT" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTURE
--------------------------------------------------------

  CREATE TABLE "FACTURE" 
   (	"ID_FACTURE" VARCHAR2(20 CHAR), 
	"ID_COMMANDE" VARCHAR2(20 CHAR), 
	"TELEPHONE" VARCHAR2(20 CHAR), 
	"DATE_FACTURE" VARCHAR2(20 CHAR), 
	"PRIX_TOTAL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FORMATIONS
--------------------------------------------------------

  CREATE TABLE "FORMATIONS" 
   (	"IDFORMATION" NUMBER(10,0), 
	"NOM" VARCHAR2(20 CHAR), 
	"PROJET" NUMBER(10,0), 
	"FORMATEUR" VARCHAR2(20 CHAR), 
	"DATEDEBUT" VARCHAR2(20 CHAR), 
	"DUREE" VARCHAR2(20 CHAR), 
	"COUT" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "FOURNISSEUR" 
   (	"ID_FOURNISSEUR" VARCHAR2(20 CHAR), 
	"NOM" VARCHAR2(20 CHAR), 
	"TELEPHONE" VARCHAR2(20 CHAR), 
	"EMAIL" VARCHAR2(20 CHAR), 
	"ADRESSE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAINTENANCE
--------------------------------------------------------

  CREATE TABLE "MAINTENANCE" 
   (	"ID_MAINTENANCE" VARCHAR2(20 CHAR), 
	"MATRICULE" VARCHAR2(20 CHAR), 
	"REF_MATERIEL" VARCHAR2(20 CHAR), 
	"DATE_MAINTENANCE" VARCHAR2(20 CHAR), 
	"TYPE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIEL
--------------------------------------------------------

  CREATE TABLE "MATERIEL" 
   (	"REF_MATERIEL" VARCHAR2(20 CHAR), 
	"MODELE" VARCHAR2(20 CHAR), 
	"TYPE" VARCHAR2(20 CHAR), 
	"NBR_MAINTENANCE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATIERE
--------------------------------------------------------

  CREATE TABLE "MATIERE" 
   (	"REFERENCE" VARCHAR2(20 CHAR), 
	"NUM_STOCK" VARCHAR2(20 CHAR), 
	"NOM" VARCHAR2(20 CHAR), 
	"QUANTITE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNELS
--------------------------------------------------------

  CREATE TABLE "PERSONNELS" 
   (	"MATRICULE" NUMBER, 
	"CIN" VARCHAR2(8 BYTE), 
	"NOM" VARCHAR2(15 BYTE), 
	"PRENOM" VARCHAR2(15 BYTE), 
	"NUMERO_TEL" VARCHAR2(8 BYTE), 
	"SEXE" VARCHAR2(20 BYTE), 
	"ETAT_CIVILE" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" DATE, 
	"GOUVERNORAT_ORIGIN" VARCHAR2(20 BYTE), 
	"GOUVERNORAT_HABITATION" VARCHAR2(20 BYTE), 
	"DIPLOME_ETUDE" VARCHAR2(20 BYTE), 
	"TYPE_CONTRAT" VARCHAR2(20 BYTE), 
	"DATE_RECRUTEMENT" DATE, 
	"DEPARTEMENT" VARCHAR2(20 BYTE), 
	"UNITE" VARCHAR2(20 BYTE), 
	"FONCTION" VARCHAR2(20 BYTE), 
	"SALAIRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUITS
--------------------------------------------------------

  CREATE TABLE "PRODUITS" 
   (	"REF_PRODUIT" VARCHAR2(20 CHAR), 
	"NUM_STOCK" VARCHAR2(20 CHAR), 
	"ID_FOURNISSEUR" VARCHAR2(20 CHAR), 
	"NOM" VARCHAR2(20 CHAR), 
	"QUANTITE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFILS
--------------------------------------------------------

  CREATE TABLE "PROFILS" 
   (	"ID" NUMBER, 
	"MATRICULE" NUMBER, 
	"NOM_UTILISATEUR" VARCHAR2(35 BYTE), 
	"MDP" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROJETS
--------------------------------------------------------

  CREATE TABLE "PROJETS" 
   (	"IDPROJET" NUMBER(10,0), 
	"NOM" VARCHAR2(20 CHAR), 
	"DEPARTEMENT" VARCHAR2(20 CHAR), 
	"TEAM_LEADER" VARCHAR2(20 CHAR), 
	"DATE_LANCEMENT" VARCHAR2(20 CHAR), 
	"COUTS_PREVUS" VARCHAR2(20 CHAR), 
	"REVENUS_PROJETES" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "STOCK" 
   (	"NUM_STOCK" VARCHAR2(20 CHAR), 
	"ETAT" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FORMATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FORMATIONS_PK" ON "FORMATIONS" ("IDFORMATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONNELS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERSONNELS_PK" ON "PERSONNELS" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONNELS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PERSONNELS_UK1" ON "PERSONNELS" ("MATRICULE", "CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROFILS_PK" ON "PROFILS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFILS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROFILS_UK1" ON "PROFILS" ("ID", "MATRICULE", "NOM_UTILISATEUR", "EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROJETS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJETS_PK" ON "PROJETS" ("IDPROJET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger IDFORMATION_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IDFORMATION_ON_INSERT" 
  BEFORE INSERT ON formations
  FOR EACH ROW
BEGIN
  SELECT idformation_sequence.nextval
  INTO :new.idformation
  FROM dual;
END;
/
ALTER TRIGGER "IDFORMATION_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ID_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ID_ON_INSERT" 
  BEFORE INSERT ON PROFILS
  FOR EACH ROW
BEGIN
  SELECT IDAI.nextval
  INTO :new.ID
  FROM dual;
END;

/
ALTER TRIGGER "ID_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger IDPROJET_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "IDPROJET_ON_INSERT" 
  BEFORE INSERT ON projets
  FOR EACH ROW
BEGIN
  SELECT idprojet_sequence.nextval
  INTO :new.idprojet
  FROM dual;
END;
/
ALTER TRIGGER "IDPROJET_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MATRICULE_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MATRICULE_ON_INSERT" 
  BEFORE INSERT ON PERSONNELS
  FOR EACH ROW
BEGIN
  SELECT MATRICULEIA.nextval
  INTO :new.MATRICULE
  FROM dual;
END;

/
ALTER TRIGGER "MATRICULE_ON_INSERT" ENABLE;
--------------------------------------------------------
--  Constraints for Table FORMATIONS
--------------------------------------------------------

  ALTER TABLE "FORMATIONS" ADD CONSTRAINT "FORMATIONS_PK" PRIMARY KEY ("IDFORMATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FORMATIONS" MODIFY ("IDFORMATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNELS
--------------------------------------------------------

  ALTER TABLE "PERSONNELS" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("FONCTION" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("UNITE" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("DEPARTEMENT" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("DATE_RECRUTEMENT" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("TYPE_CONTRAT" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("DIPLOME_ETUDE" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("GOUVERNORAT_HABITATION" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("GOUVERNORAT_ORIGIN" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("DATE_NAISSANCE" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("ETAT_CIVILE" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("SEXE" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("NUMERO_TEL" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" MODIFY ("MATRICULE" NOT NULL ENABLE);
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "PERSONNELS_UK1" UNIQUE ("MATRICULE", "CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "PERSONNELS_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_UNITE" CHECK (lower(unite) in('personnels','profils','matieres premieres','produits finis','fournisseurs','commandes achats','clients','commandes ventes','projets','formations','equipements','maintenances')) ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_TYPECONTRAT" CHECK (lower(type_Contrat) like 'cdi' or lower(type_Contrat) like 'sivp'or lower(type_Contrat) like 'cdd') ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_SEXE" CHECK (lower(sexe) in( 'masculin' ,'feminin')) ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_SALAIRE" CHECK (salaire>0) ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_PRENOM" CHECK (LENGTH(prenom)<=15) ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_ORIGIN" CHECK (lower(GOUVERNORAT_ORIGIN) in('ariana','beja','ben arous','bizerte','gabes','gafsa','jendouba','kairouan','kasserine','kebili','kef','mahdia','manouba','medenine','monastir','nabeul','sfax','sidi bouzid','siliana','sousse','tataouine','tunis','zaghouan')) ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_NULTEL" CHECK (length(numero_tel)=8) ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_NOM" CHECK (LENGTH(nom)<=15 ) ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_HABITATION" CHECK (lower(GOUVERNORAT_HABITATION) in('ariana','beja','ben arous','bizerte','gabes','gafsa','jendouba','kairouan','kasserine','kebili','kef','mahdia','manouba','medenine','monastir','nabeul','sfax','sidi bouzid','siliana','sousse','tataouine','tunis','zaghouan')) ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_FONCTION" CHECK (lower(FONCTION) in('chef de departement','chef d unite','ingenieur','technicien','ouvrier','chercheur','commercial')) ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_ETATCIVILE" CHECK (lower(etat_civile) in ('marie','celebataire','divorce')) ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_DIPLOMEETUDE" CHECK (lower(DIPLOME_ETUDE) in('bac','technicien','ingenieur','doctorant')) ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_DEPARTEMENT" CHECK (lower(departement) in('ressources humaines','stock','achats','ventes','ameliorations','materiel')) ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_DATEREC" CHECK (to_char(date_recrutement,'YYYY-MM-DD') < '2021-01-01') ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_DATE" CHECK (to_char(date_naissance,'YYYY-MM-DD') < '2000-01-01') ENABLE;
  ALTER TABLE "PERSONNELS" ADD CONSTRAINT "CH_CIN" CHECK (length(cin)=8) ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFILS
--------------------------------------------------------

  ALTER TABLE "PROFILS" MODIFY ("MATRICULE" NOT NULL ENABLE);
  ALTER TABLE "PROFILS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROFILS" ADD CONSTRAINT "PROFILS_UK" UNIQUE ("ID", "MATRICULE", "NOM_UTILISATEUR", "EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROFILS" ADD CONSTRAINT "PROFILS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJETS
--------------------------------------------------------

  ALTER TABLE "PROJETS" ADD CONSTRAINT "PROJETS_PK" PRIMARY KEY ("IDPROJET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJETS" MODIFY ("IDPROJET" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FORMATIONS
--------------------------------------------------------

  ALTER TABLE "FORMATIONS" ADD CONSTRAINT "IDPROJET_FK" FOREIGN KEY ("PROJET")
	  REFERENCES "PROJETS" ("IDPROJET") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFILS
--------------------------------------------------------

  ALTER TABLE "PROFILS" ADD CONSTRAINT "PROFILS_FK" FOREIGN KEY ("MATRICULE")
	  REFERENCES "PERSONNELS" ("MATRICULE") ON DELETE CASCADE ENABLE;
